//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikWeb_WCF.EmployeeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDTO", Namespace="http://schemas.datacontract.org/2004/07/DataLayer.Models")]
    [System.SerializableAttribute()]
    public partial class EmployeeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentDTO", Namespace="http://schemas.datacontract.org/2004/07/DataLayer.Models")]
    [System.SerializableAttribute()]
    public partial class DepartmentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeServiceReference.IEmployeeServices")]
    public interface IEmployeeServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/GetEmployees", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeesResponse")]
        TelerikWeb_WCF.EmployeeServiceReference.EmployeeDTO[] GetEmployees(int pageIndex, int pageSize, System.Nullable<int> departemntId, string keyword, string columnName, bool orderASC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/GetEmployees", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeesResponse")]
        System.Threading.Tasks.Task<TelerikWeb_WCF.EmployeeServiceReference.EmployeeDTO[]> GetEmployeesAsync(int pageIndex, int pageSize, System.Nullable<int> departemntId, string keyword, string columnName, bool orderASC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeServices/UpdateEmployeeResponse")]
        int UpdateEmployee(TelerikWeb_WCF.EmployeeServiceReference.EmployeeDTO empDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeServices/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task<int> UpdateEmployeeAsync(TelerikWeb_WCF.EmployeeServiceReference.EmployeeDTO empDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/DeleteEmployee", ReplyAction="http://tempuri.org/IEmployeeServices/DeleteEmployeeResponse")]
        void DeleteEmployee(int employeeId, int deletedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/DeleteEmployee", ReplyAction="http://tempuri.org/IEmployeeServices/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(int employeeId, int deletedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/GetDepartment", ReplyAction="http://tempuri.org/IEmployeeServices/GetDepartmentResponse")]
        TelerikWeb_WCF.EmployeeServiceReference.DepartmentDTO[] GetDepartment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/GetDepartment", ReplyAction="http://tempuri.org/IEmployeeServices/GetDepartmentResponse")]
        System.Threading.Tasks.Task<TelerikWeb_WCF.EmployeeServiceReference.DepartmentDTO[]> GetDepartmentAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServicesChannel : TelerikWeb_WCF.EmployeeServiceReference.IEmployeeServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServicesClient : System.ServiceModel.ClientBase<TelerikWeb_WCF.EmployeeServiceReference.IEmployeeServices>, TelerikWeb_WCF.EmployeeServiceReference.IEmployeeServices {
        
        public EmployeeServicesClient() {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TelerikWeb_WCF.EmployeeServiceReference.EmployeeDTO[] GetEmployees(int pageIndex, int pageSize, System.Nullable<int> departemntId, string keyword, string columnName, bool orderASC) {
            return base.Channel.GetEmployees(pageIndex, pageSize, departemntId, keyword, columnName, orderASC);
        }
        
        public System.Threading.Tasks.Task<TelerikWeb_WCF.EmployeeServiceReference.EmployeeDTO[]> GetEmployeesAsync(int pageIndex, int pageSize, System.Nullable<int> departemntId, string keyword, string columnName, bool orderASC) {
            return base.Channel.GetEmployeesAsync(pageIndex, pageSize, departemntId, keyword, columnName, orderASC);
        }
        
        public int UpdateEmployee(TelerikWeb_WCF.EmployeeServiceReference.EmployeeDTO empDto) {
            return base.Channel.UpdateEmployee(empDto);
        }
        
        public System.Threading.Tasks.Task<int> UpdateEmployeeAsync(TelerikWeb_WCF.EmployeeServiceReference.EmployeeDTO empDto) {
            return base.Channel.UpdateEmployeeAsync(empDto);
        }
        
        public void DeleteEmployee(int employeeId, int deletedBy) {
            base.Channel.DeleteEmployee(employeeId, deletedBy);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(int employeeId, int deletedBy) {
            return base.Channel.DeleteEmployeeAsync(employeeId, deletedBy);
        }
        
        public TelerikWeb_WCF.EmployeeServiceReference.DepartmentDTO[] GetDepartment() {
            return base.Channel.GetDepartment();
        }
        
        public System.Threading.Tasks.Task<TelerikWeb_WCF.EmployeeServiceReference.DepartmentDTO[]> GetDepartmentAsync() {
            return base.Channel.GetDepartmentAsync();
        }
    }
}
